NiceAesth/aiosu

- aiosu/v2/__init__.py
- aiosu/v2/clientstorage.py
- tests/test_v2/test_clientstorage.py
> Add handling for multiple clients at once

- aiosu/v2/client.py
> Revert "Add support for optional parameters when getting diff attribs"

- .github/CONTRIBUTING.rst
- aiosu/classes/beatmap.py
- aiosu/classes/events.py
- aiosu/classes/legacy/match.py
- aiosu/classes/models.py
- aiosu/classes/mods.py
- aiosu/classes/score.py
- aiosu/classes/token.py
- aiosu/classes/user.py
- aiosu/helpers.py
- aiosu/utils/performance.py
- aiosu/v1/client.py
- aiosu/v2/client.py
- aiosu/v2/clientstorage.py
> Add TYPE_CHECKING to typing imports

- aiosu/classes/beatmap.py
- aiosu/classes/score.py
- aiosu/classes/user.py
- aiosu/v1/client.py
- aiosu/v2/client.py
- tests/test_v1/test_client.py
> Add request_beatmap() for API v1 scores, fix null values in API v1, fix default limits

- .pre-commit-config.yaml
- Makefile
- aiosu/classes/events.py
- aiosu/v2/client.py
- aiosu/v2/clientstorage.py
- pyproject.toml
- tests/test_utils/test_accuracy.py
- tests/test_utils/test_pp.py
> Implement new event system

- aiosu/utils/auth.py
- docs/source/utils/index.rst
> Add auth utils

- aiosu/classes/__init__.py
- aiosu/classes/scopes.py
- aiosu/classes/token.py
- aiosu/v2/client.py
- aiosu/v2/clientstorage.py
- tests/test_misc/test_token.py
- tests/test_v2/test_client.py
- tests/test_v2/test_clientstorage.py
- tests/test_v2/test_events.py
> Add scope checking

- aiosu/classes/__init__.py
- aiosu/classes/scopes.py
- aiosu/classes/token.py
- aiosu/v1/client.py
- aiosu/v2/client.py
- aiosu/v2/clientstorage.py
- tests/test_misc/test_token.py
- tests/test_v2/test_client.py
- tests/test_v2/test_clientstorage.py
- tests/test_v2/test_events.py
> Lookup beatmap

- aiosu/classes/score.py
- aiosu/v1/client.py
- aiosu/v2/client.py
- docs/source/clients/v1/index.rst
- docs/source/clients/v2/index.rst
- tests/classes/mock.py
- tests/test_v2/test_client.py
- tests/test_v2/test_events.py
> Refactor requests

- aiosu/v2/client.py
- tests/test_v2/test_client.py
> Lookup beatmapset

- aiosu/v2/client.py
> Add revoke_token

- aiosu/classes/__init__.py
- aiosu/classes/backgrounds.py
- aiosu/classes/beatmap.py
- aiosu/classes/changelog.py
- aiosu/classes/common.py
- aiosu/classes/events.py
- aiosu/classes/legacy/match.py
- aiosu/classes/scopes.py
- aiosu/classes/score.py
- aiosu/classes/token.py
- aiosu/classes/user.py
- aiosu/v2/client.py
- examples/v2/client.py
- examples/v2/clientstorage.py
- tests/test_v2/test_client.py
- tests/test_v2/test_clientstorage.py
- tests/test_v2/test_events.py
> Changelog model

- aiosu/models/__init__.py
- aiosu/models/kudosu.py
- aiosu/v2/client.py
- docs/source/models/index.rst
- tests/data/v2/kudosu_history.json
- tests/test_v2/test_client.py
> Get user kudosu

- aiosu/v1/client.py
- aiosu/v2/client.py
> Handle downloading of osu! maps from original /osu/ endpoint

- pyproject.toml
> Downgrade sphinx

- aiosu/__init__.py
- aiosu/models/__init__.py
- aiosu/models/legacy/__init__.py
- aiosu/models/legacy/replay.py
- aiosu/models/replay.py
- aiosu/utils/__init__.py
- aiosu/utils/auth.py
- aiosu/utils/binary.py
- aiosu/utils/replay.py
- aiosu/v1/client.py
- docs/source/models/index.rst
- docs/source/utils/index.rst
- examples/utils.py
- tests/test_utils/test_replay.py
- tests/test_v1/test_client.py
> Parse replay

- aiosu/utils/binary.py
> [utils] Fix default LZMA format for replay data

- aiosu/events.py
- aiosu/models/replay.py
- aiosu/models/scopes.py
- aiosu/utils/auth.py
- aiosu/v2/client.py
- aiosu/v2/clientstorage.py
> Better scopes

- aiosu/v2/client.py
- tests/test_v2/test_client.py
> Cleanup for 1.0.0

- aiosu/v2/client.py
> fix: create chat channel target_ids

- aiosu/v2/client.py
> docs: update UUID private message docs

- aiosu/utils/__init__.py
- aiosu/utils/accuracy.py
> fix: account for scorev2 in mania accuracy

- aiosu/utils/accuracy.py
> feat: account for sv2 in std acc; style: improve code style

- aiosu/models/beatmap.py
- aiosu/models/user.py
> fix: alias 2x images; add 2x for tournament banner

- aiosu/models/chat.py
> fix: remove deprecated content_html

- aiosu/v1/client.py
> fix: content type on v1 endpoints

- aiosu/v2/client.py
- aiosu/v2/clientstorage.py
> fix: prepare client properly; warn on custom repo

- Makefile
> fix: prevent releasing outside master

- aiosu/v2/client.py
> fix: update token if provided and already exists in repo

- aiosu/v2/clientstorage.py
> fix: missing session id in get client call

- aiosu/exceptions.py
- aiosu/v2/client.py
- aiosu/v2/clientstorage.py
> feat: add exception for get_client; fix: handle bools in get requests

- aiosu/models/base.py
- aiosu/models/beatmap.py
- aiosu/models/gamemode.py
- aiosu/models/legacy/match.py
- aiosu/models/replay.py
- aiosu/models/user.py
- aiosu/v1/client.py
- aiosu/v2/client.py
- tests/test_misc/test_models.py
> fix: serialize enums correctly

- aiosu/models/beatmap.py
> feat: allow getting covers from bmapset id

- aiosu/models/base.py
- aiosu/models/beatmap.py
- aiosu/models/gamemode.py
- aiosu/models/mods.py
- aiosu/models/user.py
> fix: typing on _missing_ methods

- aiosu/models/user.py
> feat: add user rank highest

- aiosu/models/user.py
> feat: add pp per playtime property to user stats

- aiosu/v2/client.py
> fix: re-open session if closed

- aiosu/models/user.py
> fix: more lenient user query type lookups

- aiosu/models/lazer.py
- aiosu/models/score.py
> fix: improve score url lookups

- aiosu/models/score.py
> feat: use passed attr to avoid completion calculation

- aiosu/events.py
- aiosu/models/oauthtoken.py
- aiosu/models/score.py
- aiosu/utils/performance.py
- aiosu/v1/client.py
- aiosu/v2/client.py
- aiosu/v2/clientstorage.py
- aiosu/v2/repository/oauthtoken.py
> style: add __slots__

- aiosu/v2/client.py
- aiosu/v2/clientstorage.py
- aiosu/v2/repository/oauthtoken.py
- examples/v2/custom_repository.py
- tests/test_v2/test_client.py
- tests/test_v2/test_clientstorage.py
> feat: add token revoking

- aiosu/utils/replay.py
- aiosu/v1/client.py
- aiosu/v2/client.py
- tests/test_v2/test_client.py
> feat: set session to none on close

- aiosu/models/common.py
- aiosu/v2/client.py
- aiosu/v2/clientstorage.py
> fix: preserve original function types

- .pre-commit-config.yaml
- aiosu/models/scopes.py
- aiosu/v2/client.py
- pyproject.toml
> feat: make public scope optional

- aiosu/v2/client.py
> style: remove headers from session refresh

- .pre-commit-config.yaml
- Makefile
- aiosu/v1/client.py
- aiosu/v2/client.py
> chore: maintenance in preparation for v2 

- docs/source/conf.py
- docs/source/index.rst
- pyproject.toml
`sphinx-rtd-theme` is quite outdated and does not support `Sphinx v7`.
> feat: change docs to furo theme

- aiosu/models/__init__.py
- aiosu/models/files/__init__.py
- aiosu/models/files/replay.py
- aiosu/utils/replay.py
- docs/source/models/index.rst
- examples/utils.py
- tests/test_utils/test_replay.py
> feat: move file related models to separate directory

- aiosu/models/artist.py
- aiosu/models/beatmap.py
- aiosu/models/changelog.py
- aiosu/models/chat.py
- aiosu/models/comment.py
- aiosu/models/common.py
- aiosu/models/lazer.py
- aiosu/models/multiplayer.py
- aiosu/models/news.py
- aiosu/models/spotlight.py
- aiosu/v2/client.py
- docs/source/models/index.rst
> feat: add more literal types

- aiosu/models/common.py
> fix: only cast to datetime if str

- aiosu/models/event.py
- aiosu/v2/client.py
- tests/data/v2/multiple_cursor_event.json
- tests/test_v2/test_client.py
> feat: add events endpoint

- aiosu/models/user.py
> fix: change type of `UserLevel.progress` to int

- aiosu/models/user.py
- aiosu/utils/performance.py
This will return 0 if the list is empty or data[0] if list has a single element.
> fix: possible division by 0 in `average_gain`

- aiosu/models/beatmap.py
- aiosu/models/common.py
- aiosu/models/event.py
- aiosu/models/lazer.py
- aiosu/models/score.py
- aiosu/models/user.py
- Removed aliased properties from being serialized (removed `@computed_field`)
- Changed more expensive properties to `@cached_property`
- Added `has_replay` alias to `LazerScore`
With this change, hopefully we are ready for release.
> feat: model property check pass

- aiosu/models/user.py
> feat: add @2x field for user badge image

- aiosu/models/mods.py
- tests/test_misc/test_models.py
> tests: mod type testing

- aiosu/helpers.py
- aiosu/models/base.py
- aiosu/models/beatmap.py
- aiosu/models/common.py
- aiosu/models/gamemode.py
- aiosu/models/lazer.py
- aiosu/models/legacy/match.py
- aiosu/models/mods.py
- aiosu/models/multiplayer.py
- aiosu/models/oauthtoken.py
- aiosu/models/score.py
- aiosu/models/user.py
- aiosu/utils/accuracy.py
- aiosu/utils/binary.py
- aiosu/v1/client.py
- aiosu/v2/client.py
- aiosu/v2/clientstorage.py
- tests/test_v1/test_client.py
- tests/test_v2/test_client.py
Prefer usage of `object` over Any
Prefer usage of `Mapping` / `MutableMapping` for public data
> refactor: improve typing

- aiosu/models/user.py
> feat: make `UserGradeCounts` attributes not nullable

- aiosu/helpers.py
- aiosu/models/beatmap.py
- aiosu/v2/client.py
- tests/generate/main.py
- tests/test_v2/test_client.py
Based on:
https://github.com/ppy/osu-web/blob/4abad84c7a5a1f009cb3e3ce7f13eb05b4a89971/app/Libraries/Search/BeatmapsetQueryParser.php 
https://github.com/ppy/osu-web/blob/b00c4191403d45969fca1134e5a5fa2ab825a5e2/app/Http/Controllers/BeatmapsetsController.php#L365 
https://github.com/ppy/osu-web/blob/b00c4191403d45969fca1134e5a5fa2ab825a5e2/tests/api_routes.json#L952
> fix: properly implement beatmapset search

- aiosu/models/user.py
missed this one in the last release
> feat: add support for multiple tournament banners

- aiosu/models/beatmap.py
- aiosu/models/changelog.py
- aiosu/models/multiplayer.py
- aiosu/models/news.py
- aiosu/models/user.py
> feat: update models to be in line with osu-web

- aiosu/models/lazer.py
> feat: add new lazer replay attributes

- aiosu/v2/client.py
> feat: make missing scope exceptions more verbose

- aiosu/models/lazer.py
- aiosu/models/score.py
api still does not return F ranks
> fix: re-add pass validator

- aiosu/v2/client.py
> feat: add `legacy_only` param to `get_beatmap_scores`

- pyproject.toml
> chore: update to pytest 8.0.0

- aiosu/models/artist.py
see https://github.com/ppy/osu-web/blob/7ea09d7fbb1c835200915517d22349ac43e7ffea/app/Models/Artist.php
> feat: update artist models with osu-web attributes

- aiosu/utils/auth.py
- aiosu/v1/client.py
- aiosu/v2/client.py
> feat: preserve status code on content type exceptions

- aiosu/models/lazer.py
- aiosu/utils/binary.py
> chore: misc changes

- aiosu/v2/client.py
> feat: add `exclusive_only` parameter to `get_featured_artists()`

- aiosu/models/common.py
> fix: hotfix score_type nullable in pinattributes

- aiosu/models/user.py
> feat: add new `profile_hue` attribute to user model

- aiosu/models/common.py
> fix: work around mypy's partial plugin being shit

- aiosu/models/user.py
todo: update tests to include teams
> feat: add user teams to user object

- aiosu/v2/client.py
- tests/test_v2/test_client.py
> fix: only cast to BeatmapPackType if not instance
